export type ToolKind = "stats" | "transform" | "find-replace" | "compare" | "speech-tts" | "speech-stt";

export type ToolCatalogItem = {
  name: string;
  slug: string;
  kind: ToolKind;
  description: string;
  relatedTools: string[];
};

export const toolCatalog: ToolCatalogItem[] = [
  { name: "Word Counter", slug: "word-counter", kind: "stats", description: "Count words, characters, sentences, and paragraphs instantly.", relatedTools: ["character-counter", "count-sentences", "count-paragraphs"] },
  { name: "Character Counter", slug: "character-counter", kind: "stats", description: "Measure characters with and without spaces in real time.", relatedTools: ["word-counter", "count-vowels", "count-consonants"] },
  { name: "Uppercase Converter", slug: "uppercase-converter", kind: "transform", description: "Convert text to UPPERCASE for emphasis and formatting.", relatedTools: ["lowercase-converter", "title-case-converter", "text-capitalizer"] },
  { name: "Lowercase Converter", slug: "lowercase-converter", kind: "transform", description: "Convert text to lowercase for normalization workflows.", relatedTools: ["uppercase-converter", "sentence-case-converter", "text-to-url-slug"] },
  { name: "Title Case Converter", slug: "title-case-converter", kind: "transform", description: "Capitalize words for headings and titles.", relatedTools: ["sentence-case-converter", "text-capitalizer", "uppercase-converter"] },
  { name: "Sentence Case Converter", slug: "sentence-case-converter", kind: "transform", description: "Format text into sentence-style capitalization.", relatedTools: ["title-case-converter", "lowercase-converter", "remove-extra-spaces"] },
  { name: "Remove Duplicate Lines", slug: "remove-duplicate-lines", kind: "transform", description: "Remove duplicate lines while preserving original order.", relatedTools: ["sort-lines-alphabetically", "remove-extra-spaces", "shuffle-lines"] },
  { name: "Remove Extra Spaces", slug: "remove-extra-spaces", kind: "transform", description: "Collapse repeated spaces and clean messy text.", relatedTools: ["trim-text", "remove-line-breaks", "remove-duplicate-lines"] },
  { name: "Text Reverser", slug: "text-reverser", kind: "transform", description: "Reverse text characters for testing and fun.", relatedTools: ["reverse-words", "shuffle-lines", "binary-to-text"] },
  { name: "Remove Line Breaks", slug: "remove-line-breaks", kind: "transform", description: "Join wrapped lines into one clean paragraph.", relatedTools: ["remove-extra-spaces", "trim-text", "text-wrap"] },
  { name: "Find & Replace", slug: "find-replace", kind: "find-replace", description: "Find words and replace text instantly.", relatedTools: ["remove-punctuation", "remove-special-characters", "text-diff-checker"] },
  { name: "Text to URL Slug", slug: "text-to-url-slug", kind: "transform", description: "Convert text into clean SEO-friendly URL slugs.", relatedTools: ["text-slugify", "kebab-case-converter", "lowercase-converter"] },
  { name: "Remove Punctuation", slug: "remove-punctuation", kind: "transform", description: "Strip punctuation marks from text.", relatedTools: ["remove-special-characters", "remove-numbers", "trim-text"] },
  { name: "Count Sentences", slug: "count-sentences", kind: "transform", description: "Count sentences in your content quickly.", relatedTools: ["word-counter", "count-paragraphs", "character-counter"] },
  { name: "Count Paragraphs", slug: "count-paragraphs", kind: "transform", description: "Count paragraph blocks in text.", relatedTools: ["word-counter", "count-sentences", "remove-line-breaks"] },
  { name: "Count Vowels", slug: "count-vowels", kind: "transform", description: "Count vowel letters in any text.", relatedTools: ["count-consonants", "character-counter", "word-frequency-counter"] },
  { name: "Count Consonants", slug: "count-consonants", kind: "transform", description: "Count consonant letters in text.", relatedTools: ["count-vowels", "character-counter", "word-frequency-counter"] },
  { name: "Text Encryptor", slug: "text-encryptor", kind: "transform", description: "Encrypt plain text into encoded output.", relatedTools: ["text-decryptor", "text-to-binary", "encode-html-entities"] },
  { name: "Text Decryptor", slug: "text-decryptor", kind: "transform", description: "Decode encrypted text back to readable text.", relatedTools: ["text-encryptor", "binary-to-text", "decode-html-entities"] },
  { name: "Remove Numbers", slug: "remove-numbers", kind: "transform", description: "Remove digits from text instantly.", relatedTools: ["remove-special-characters", "remove-punctuation", "trim-text"] },
  { name: "Remove Special Characters", slug: "remove-special-characters", kind: "transform", description: "Keep only letters, numbers, and spaces.", relatedTools: ["remove-punctuation", "remove-numbers", "text-to-url-slug"] },
  { name: "Trim Text", slug: "trim-text", kind: "transform", description: "Trim leading and trailing whitespace from text.", relatedTools: ["remove-extra-spaces", "remove-line-breaks", "unwrap-text"] },
  { name: "Sort Lines Alphabetically", slug: "sort-lines-alphabetically", kind: "transform", description: "Sort lines A to Z.", relatedTools: ["sort-lines-reverse", "shuffle-lines", "remove-duplicate-lines"] },
  { name: "Sort Lines Reverse", slug: "sort-lines-reverse", kind: "transform", description: "Sort lines Z to A.", relatedTools: ["sort-lines-alphabetically", "shuffle-lines", "remove-duplicate-lines"] },
  { name: "Shuffle Lines", slug: "shuffle-lines", kind: "transform", description: "Randomly shuffle lines in your text.", relatedTools: ["sort-lines-alphabetically", "remove-duplicate-lines", "text-reverser"] },
  { name: "Convert to Morse Code", slug: "convert-to-morse-code", kind: "transform", description: "Encode text into Morse code.", relatedTools: ["decode-morse-code", "text-to-binary", "text-encryptor"] },
  { name: "Decode Morse Code", slug: "decode-morse-code", kind: "transform", description: "Decode Morse code into plain text.", relatedTools: ["convert-to-morse-code", "binary-to-text", "text-decryptor"] },
  { name: "Binary to Text", slug: "binary-to-text", kind: "transform", description: "Convert binary values to readable text.", relatedTools: ["text-to-binary", "decode-morse-code", "text-decryptor"] },
  { name: "Text to Binary", slug: "text-to-binary", kind: "transform", description: "Convert text to binary code.", relatedTools: ["binary-to-text", "convert-to-morse-code", "text-encryptor"] },
  { name: "Lorem Ipsum Generator", slug: "lorem-ipsum-generator", kind: "transform", description: "Generate lorem ipsum placeholder paragraphs.", relatedTools: ["random-text-generator", "word-counter", "text-wrap"] },
  { name: "Random Text Generator", slug: "random-text-generator", kind: "transform", description: "Generate random words for testing layouts.", relatedTools: ["lorem-ipsum-generator", "text-wrap", "word-counter"] },
  { name: "Text Diff Checker", slug: "text-diff-checker", kind: "compare", description: "Compare two text blocks and highlight differences.", relatedTools: ["text-similarity-checker", "find-replace", "remove-extra-spaces"] },
  { name: "Text Similarity Checker", slug: "text-similarity-checker", kind: "compare", description: "Estimate similarity percentage between two texts.", relatedTools: ["text-diff-checker", "word-frequency-counter", "character-counter"] },
  { name: "Pig Latin Converter", slug: "pig-latin-converter", kind: "transform", description: "Convert English words into Pig Latin.", relatedTools: ["reverse-words", "text-capitalizer", "lowercase-converter"] },
  { name: "Camel Case Converter", slug: "camel-case-converter", kind: "transform", description: "Convert text into camelCase format.", relatedTools: ["snake-case-converter", "kebab-case-converter", "text-slugify"] },
  { name: "Snake Case Converter", slug: "snake-case-converter", kind: "transform", description: "Convert text into snake_case format.", relatedTools: ["camel-case-converter", "kebab-case-converter", "text-slugify"] },
  { name: "Kebab Case Converter", slug: "kebab-case-converter", kind: "transform", description: "Convert text into kebab-case format.", relatedTools: ["camel-case-converter", "snake-case-converter", "text-to-url-slug"] },
  { name: "Text Wrap", slug: "text-wrap", kind: "transform", description: "Wrap text to a fixed width.", relatedTools: ["unwrap-text", "lorem-ipsum-generator", "remove-line-breaks"] },
  { name: "Unwrap Text", slug: "unwrap-text", kind: "transform", description: "Remove hard wraps and unwrap paragraphs.", relatedTools: ["text-wrap", "remove-line-breaks", "trim-text"] },
  { name: "Remove HTML Tags", slug: "remove-html-tags", kind: "transform", description: "Strip HTML tags and keep plain text.", relatedTools: ["encode-html-entities", "decode-html-entities", "remove-special-characters"] },
  { name: "Encode HTML Entities", slug: "encode-html-entities", kind: "transform", description: "Encode special characters as HTML entities.", relatedTools: ["decode-html-entities", "remove-html-tags", "text-encryptor"] },
  { name: "Decode HTML Entities", slug: "decode-html-entities", kind: "transform", description: "Decode HTML entities into characters.", relatedTools: ["encode-html-entities", "remove-html-tags", "text-decryptor"] },
  { name: "Text to Speech", slug: "text-to-speech", kind: "speech-tts", description: "Read text aloud using browser speech synthesis.", relatedTools: ["speech-to-text", "word-counter", "sentence-case-converter"] },
  { name: "Speech to Text", slug: "speech-to-text", kind: "speech-stt", description: "Convert spoken words into text in your browser.", relatedTools: ["text-to-speech", "word-counter", "character-counter"] },
  { name: "Acronym Generator", slug: "acronym-generator", kind: "transform", description: "Generate acronyms from phrases.", relatedTools: ["expand-acronyms", "text-capitalizer", "uppercase-converter"] },
  { name: "Expand Acronyms", slug: "expand-acronyms", kind: "transform", description: "Expand common acronyms into full forms.", relatedTools: ["acronym-generator", "find-replace", "text-capitalizer"] },
  { name: "Text Slugify", slug: "text-slugify", kind: "transform", description: "Slugify text for clean URLs and identifiers.", relatedTools: ["text-to-url-slug", "kebab-case-converter", "lowercase-converter"] },
  { name: "Text Capitalizer", slug: "text-capitalizer", kind: "transform", description: "Capitalize the first letter of each word.", relatedTools: ["title-case-converter", "sentence-case-converter", "uppercase-converter"] },
  { name: "Reverse Words", slug: "reverse-words", kind: "transform", description: "Reverse word order in a sentence.", relatedTools: ["text-reverser", "pig-latin-converter", "word-frequency-counter"] },
  { name: "Word Frequency Counter", slug: "word-frequency-counter", kind: "transform", description: "Count frequency of each word in text.", relatedTools: ["word-counter", "text-similarity-checker", "count-vowels"] },
  { name: "Palindrome Checker", slug: "palindrome-checker", kind: "transform", description: "Check whether text reads the same backward.", relatedTools: ["text-reverser", "reverse-words", "character-counter"] },
  { name: "Reading Time Estimator", slug: "reading-time-estimator", kind: "transform", description: "Estimate reading time for your content.", relatedTools: ["word-counter", "count-sentences", "count-paragraphs"] },
  { name: "Alternating Case Converter", slug: "alternating-case-converter", kind: "transform", description: "Convert text to alternating case style.", relatedTools: ["inverse-case-converter", "random-case-converter", "uppercase-converter"] },
  { name: "Inverse Case Converter", slug: "inverse-case-converter", kind: "transform", description: "Invert uppercase and lowercase characters.", relatedTools: ["alternating-case-converter", "random-case-converter", "lowercase-converter"] },
  { name: "Random Case Converter", slug: "random-case-converter", kind: "transform", description: "Randomize capitalization for each letter.", relatedTools: ["alternating-case-converter", "inverse-case-converter", "text-capitalizer"] },
  { name: "Remove Accents", slug: "remove-accents", kind: "transform", description: "Strip accents and diacritics from text.", relatedTools: ["text-slugify", "remove-special-characters", "text-to-url-slug"] },
  { name: "Remove Stop Words", slug: "remove-stop-words", kind: "transform", description: "Remove common stop words from text.", relatedTools: ["keyword-density-checker", "word-frequency-counter", "lowercase-converter"] },
  { name: "Remove Comments", slug: "remove-comments", kind: "transform", description: "Remove inline and block comments from code-like text.", relatedTools: ["remove-extra-spaces", "json-to-yaml", "yaml-to-json"] },
  { name: "Keyword Density Checker", slug: "keyword-density-checker", kind: "transform", description: "Analyze top keyword density percentages.", relatedTools: ["word-frequency-counter", "readability-checker", "word-counter"] },
  { name: "Readability Checker", slug: "readability-checker", kind: "transform", description: "Estimate readability with Flesch score and stats.", relatedTools: ["keyword-density-checker", "count-sentences", "word-counter"] },
  { name: "N-Gram Generator", slug: "ngram-generator", kind: "transform", description: "Generate and count frequent n-grams.", relatedTools: ["word-frequency-counter", "keyword-density-checker", "text-similarity-checker"] },
  { name: "Text to Hex", slug: "text-to-hex", kind: "transform", description: "Convert text into hexadecimal values.", relatedTools: ["hex-to-text", "text-to-binary", "text-to-ascii"] },
  { name: "Hex to Text", slug: "hex-to-text", kind: "transform", description: "Decode hexadecimal values into text.", relatedTools: ["text-to-hex", "binary-to-text", "ascii-to-text"] },
  { name: "Text to Octal", slug: "text-to-octal", kind: "transform", description: "Convert text into octal values.", relatedTools: ["octal-to-text", "text-to-binary", "text-to-hex"] },
  { name: "Octal to Text", slug: "octal-to-text", kind: "transform", description: "Decode octal values into text.", relatedTools: ["text-to-octal", "binary-to-text", "ascii-to-text"] },
  { name: "Text to ASCII", slug: "text-to-ascii", kind: "transform", description: "Convert text into ASCII decimal codes.", relatedTools: ["ascii-to-text", "text-to-hex", "text-to-binary"] },
  { name: "ASCII to Text", slug: "ascii-to-text", kind: "transform", description: "Convert ASCII decimal codes to text.", relatedTools: ["text-to-ascii", "hex-to-text", "binary-to-text"] },
  { name: "ROT13 Converter", slug: "rot13", kind: "transform", description: "Apply ROT13 substitution to text.", relatedTools: ["caesar-cipher", "text-encryptor", "text-decryptor"] },
  { name: "Caesar Cipher", slug: "caesar-cipher", kind: "transform", description: "Shift letters with Caesar cipher.", relatedTools: ["rot13", "text-encryptor", "text-decryptor"] },
  { name: "Blog Title Generator", slug: "blog-title-generator", kind: "transform", description: "Generate blog title ideas from a topic.", relatedTools: ["meta-description-generator", "keyword-density-checker", "word-counter"] },
  { name: "Meta Description Generator", slug: "meta-description-generator", kind: "transform", description: "Generate SEO-friendly meta descriptions.", relatedTools: ["blog-title-generator", "character-counter", "keyword-density-checker"] },
  { name: "Glitch Text Generator", slug: "glitch-text-generator", kind: "transform", description: "Create glitch-styled text effects.", relatedTools: ["zalgo-text-generator", "random-case-converter", "text-obfuscator"] },
  { name: "Zalgo Text Generator", slug: "zalgo-text-generator", kind: "transform", description: "Generate chaotic zalgo text effects.", relatedTools: ["glitch-text-generator", "random-case-converter", "text-reverser"] },
  { name: "JSON to CSV", slug: "json-to-csv", kind: "transform", description: "Convert JSON arrays into CSV format.", relatedTools: ["csv-to-json", "json-to-yaml", "yaml-to-json"] },
  { name: "CSV to JSON", slug: "csv-to-json", kind: "transform", description: "Convert CSV rows into JSON objects.", relatedTools: ["json-to-csv", "json-to-yaml", "yaml-to-json"] },
  { name: "YAML to JSON", slug: "yaml-to-json", kind: "transform", description: "Convert YAML-like key/value data to JSON.", relatedTools: ["json-to-yaml", "csv-to-json", "json-to-csv"] },
  { name: "JSON to YAML", slug: "json-to-yaml", kind: "transform", description: "Convert JSON objects to YAML-like output.", relatedTools: ["yaml-to-json", "json-to-csv", "csv-to-json"] },
  { name: "Text Obfuscator", slug: "text-obfuscator", kind: "transform", description: "Mask letters and numbers in text.", relatedTools: ["glitch-text-generator", "remove-special-characters", "text-encryptor"] },
];
