import {
  base64Decoder,
  base64Encoder,
  cssFormatter,
  cssMinifier,
  htmlFormatter,
  htmlMinifier,
  jsFormatter,
  jsMinifier,
  jsonFormatter,
  jsonValidator,
  jsonViewer,
  sqlFormatter,
  urlDecoder,
  urlEncoder,
  xmlFormatter,
} from "./devToolTransforms";
import {
  acronymGenerator,
  alternatingCase,
  binaryToText,
  blogTitleGenerator,
  caesarCipher,
  csvToJson,
  countConsonants,
  glitchText,
  hexToText,
  inverseCase,
  jsonToCsv,
  jsonToYaml,
  countParagraphsOnly,
  countSentencesOnly,
  countVowels,
  keywordDensity,
  metaDescriptionGenerator,
  ngramGenerator,
  octalToText,
  encodeHtmlEntities,
  decodeHtmlEntities,
  loremIpsumGenerator,
  morseToText,
  randomCase,
  randomTextGenerator,
  readabilityScore,
  removeAccents,
  removeCodeComments,
  removeDuplicateLines,
  removeExtraSpaces,
  removeHtmlTags,
  removeLineBreaks,
  removeNumbers,
  removePunctuation,
  removeSpecialCharacters,
  removeStopWords,
  rot13,
  reverseWords,
  textObfuscator,
  textToAscii,
  asciiToText,
  textToHex,
  textToOctal,
  simpleDecrypt,
  simpleEncrypt,
  sortLinesAlphabetically,
  sortLinesReverse,
  textCapitalizer,
  textToBinary,
  textToMorse,
  textToUrlSlug,
  textWrap,
  toLowercase,
  toCamelCase,
  toKebabCase,
  toSentenceCase,
  toSnakeCase,
  toTitleCase,
  toUppercase,
  toPigLatin,
  trimText,
  unwrapText,
  wordFrequencyCounter,
  yamlToJson,
  zalgoText,
  shuffleLines,
} from "./textTransforms";

/** Slugs that use TransformToolClient with a pure string transform. */
export const transformComputeBySlug: Record<string, (s: string) => string> = {
  "uppercase-converter": toUppercase,
  "lowercase-converter": toLowercase,
  "title-case-converter": toTitleCase,
  "sentence-case-converter": toSentenceCase,
  "remove-duplicate-lines": removeDuplicateLines,
  "remove-extra-spaces": removeExtraSpaces,
  "remove-line-breaks": removeLineBreaks,
  "text-to-url-slug": textToUrlSlug,
  "remove-punctuation": removePunctuation,
  "count-sentences": countSentencesOnly,
  "count-paragraphs": countParagraphsOnly,
  "count-vowels": countVowels,
  "count-consonants": countConsonants,
  "text-encryptor": simpleEncrypt,
  "text-decryptor": simpleDecrypt,
  "remove-numbers": removeNumbers,
  "remove-special-characters": removeSpecialCharacters,
  "trim-text": trimText,
  "sort-lines-alphabetically": sortLinesAlphabetically,
  "sort-lines-reverse": sortLinesReverse,
  "shuffle-lines": shuffleLines,
  "convert-to-morse-code": textToMorse,
  "decode-morse-code": morseToText,
  "binary-to-text": binaryToText,
  "text-to-binary": textToBinary,
  "lorem-ipsum-generator": loremIpsumGenerator,
  "random-text-generator": randomTextGenerator,
  "pig-latin-converter": toPigLatin,
  "camel-case-converter": toCamelCase,
  "snake-case-converter": toSnakeCase,
  "kebab-case-converter": toKebabCase,
  "text-wrap": textWrap,
  "unwrap-text": unwrapText,
  "remove-html-tags": removeHtmlTags,
  "encode-html-entities": encodeHtmlEntities,
  "decode-html-entities": decodeHtmlEntities,
  "acronym-generator": acronymGenerator,
  "expand-acronyms": (s) => s.replace(/\bAPI\b/g, "Application Programming Interface").replace(/\bSEO\b/g, "Search Engine Optimization").replace(/\bHTML\b/g, "HyperText Markup Language"),
  "text-slugify": textToUrlSlug,
  "text-capitalizer": textCapitalizer,
  "reverse-words": reverseWords,
  "word-frequency-counter": wordFrequencyCounter,
  "palindrome-checker": (s) => {
    const normalized = s.toLowerCase().replace(/[^a-z0-9]/g, "");
    if (!normalized) return "Enter text to check palindrome.";
    return normalized === [...normalized].reverse().join("")
      ? "Yes — this is a palindrome."
      : "No — this is not a palindrome.";
  },
  "reading-time-estimator": (s) => {
    const words = s.trim() ? s.trim().split(/\s+/).length : 0;
    const minutes = words / 200;
    return `${words} words\nEstimated reading time: ${Math.max(1, Math.ceil(minutes))} minute(s)`;
  },
  "alternating-case-converter": alternatingCase,
  "inverse-case-converter": inverseCase,
  "random-case-converter": randomCase,
  "remove-accents": removeAccents,
  "remove-stop-words": removeStopWords,
  "remove-comments": removeCodeComments,
  "keyword-density-checker": keywordDensity,
  "readability-checker": readabilityScore,
  "ngram-generator": ngramGenerator,
  "text-to-hex": textToHex,
  "hex-to-text": hexToText,
  "text-to-octal": textToOctal,
  "octal-to-text": octalToText,
  "text-to-ascii": textToAscii,
  "ascii-to-text": asciiToText,
  rot13: rot13,
  "caesar-cipher": (s) => caesarCipher(s, 3),
  "blog-title-generator": blogTitleGenerator,
  "meta-description-generator": metaDescriptionGenerator,
  "glitch-text-generator": glitchText,
  "zalgo-text-generator": zalgoText,
  "json-to-csv": jsonToCsv,
  "csv-to-json": csvToJson,
  "yaml-to-json": yamlToJson,
  "json-to-yaml": jsonToYaml,
  "text-obfuscator": textObfuscator,
  "json-formatter": jsonFormatter,
  "json-validator": jsonValidator,
  "json-viewer": jsonViewer,
  "base64-encoder": base64Encoder,
  "base64-decoder": base64Decoder,
  "url-encoder": urlEncoder,
  "url-decoder": urlDecoder,
  "html-formatter": htmlFormatter,
  "css-formatter": cssFormatter,
  "js-formatter": jsFormatter,
  "sql-formatter": sqlFormatter,
  "xml-formatter": xmlFormatter,
  "html-minifier": htmlMinifier,
  "css-minifier": cssMinifier,
  "js-minifier": jsMinifier,
};
