/** Lightweight example list for empty-state preview — no presets import. */
export const EXAMPLE_PREVIEW_ITEMS = [
  "Birthday cake",
  "Balloons",
  "Candles",
  "Party hat",
  "Gift wrap",
  "Confetti",
  "Streaming music",
  "Pizza slices",
  "Photo booth",
  "Dance floor",
  "Ice cream",
  "Goodie bag",
  "Sparkler",
  "Friendship bracelet",
  "Karaoke",
  "Pinata",
  "Cupcakes",
  "Board games",
  "Glow sticks",
  "Thank-you notes",
  "Party playlist",
  "Streamers",
  "Lemonade",
  "Costume props",
  "Group selfie",
];
